services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: brabank
      POSTGRES_PASSWORD: brabank
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth:
    build: ./brabank.auth
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://postgres:5432/auth_db
    ports:
      - "8081:8081"